// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shree_om.Data;

#nullable disable

namespace shree_om.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260225050203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("shree_om.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Premium door handle collection",
                            Name = "Door Handles"
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-security lock systems",
                            Name = "Locks"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Durable hinge solutions",
                            Name = "Hinges"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Complete hardware sets",
                            Name = "Hardware Sets"
                        });
                });

            modelBuilder.Entity("shree_om.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-quality stainless steel SS304 door handle with chrome finish.",
                            DiscountPercent = 31,
                            ImageUrl = "/images/handle-chrome.jpg",
                            IsFeatured = true,
                            Name = "Premium SS304 Door Handle – Chrome",
                            OriginalPrice = 1299m,
                            Price = 899m,
                            Rating = 4.6m,
                            ReviewCount = 784,
                            Stock = 124
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium heavy-duty lock set for maximum security.",
                            DiscountPercent = 0,
                            ImageUrl = "/images/lock-set.jpg",
                            IsFeatured = true,
                            Name = "Heavy Duty Lock Set Premium",
                            OriginalPrice = 1800m,
                            Price = 1250m,
                            Rating = 4.8m,
                            ReviewCount = 93,
                            Stock = 1196
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sleek matte black door handle for modern interiors.",
                            DiscountPercent = 21,
                            ImageUrl = "/images/handle-black.jpg",
                            IsFeatured = true,
                            Name = "Door Handle Matt Black Finish",
                            OriginalPrice = 749m,
                            Price = 749m,
                            Rating = 4.5m,
                            ReviewCount = 267,
                            Stock = 195
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Industrial-grade hinges, sold as a pack of 2.",
                            DiscountPercent = 0,
                            ImageUrl = "/images/hinge-set.jpg",
                            IsFeatured = true,
                            Name = "Heavy Duty Hinge Set (Pack of 2)",
                            OriginalPrice = 599m,
                            Price = 599m,
                            Rating = 4.6m,
                            ReviewCount = 421,
                            Stock = 1236
                        });
                });

            modelBuilder.Entity("shree_om.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("shree_om.Models.Product", b =>
                {
                    b.HasOne("shree_om.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("shree_om.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
